[FIX]azure-piplines.yml and README.md

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -4,8 +4,8 @@ trigger:
 pr:
 - '*'
 
-pool:
-  vmImage: ubuntu-latest
+# pool:
+#   vmImage: ubuntu-latest
 
 stages:
 - stage: Build
@@ -32,31 +32,31 @@ stages:
         versionSpec: '3.8'
         addToPath: true
     - script: |
-        ssh -i /path/to/your/private-key.pem centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com "sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose"
-        scp -i /path/to/your/private-key.pem -r /home/counter-service centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com:/home/counter-service/
-        ssh -i /path/to/your/private-key.pem centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com "cd /home/counter-service/ && docker-compose up -d $(Build.BuildId)"
+        ssh -i $(Agent.TempDirectory)/devops-exam.pem centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com "sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose"
+        scp -i $(Agent.TempDirectory)/devops-exam.pem -r /home/counter-service centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com:/home/counter-service/
+        ssh -i $(Agent.TempDirectory)/devops-exam.pem centos@ec2-3-125-43-16.eu-central-1.compute.amazonaws.com "cd /home/counter-service/ && docker-compose up -d $(Build.BuildId)"
       displayName: 'Deploy to EC2 via SSH'
 
-# - stage: HealthCheck
-#   jobs:
-#   - job: HealthCheckJob
-#     steps:
-#     - task: UsePythonVersion@0
-#       inputs:
-#         versionSpec: '3.8'  # Use the appropriate Python version
-#         addToPath: true
-#     - script: |
-#         # Perform a health check here, e.g., using a tool like curl or requests
-#         # Wait for the service to start before checking
-#         sleep 10  # Adjust the sleep duration as needed
-#         response=$(curl -Is http://ec2-3-125-43-16.eu-central-1.compute.amazonaws.com/ | head -n 1)
-#         if [[ $response == *"200 OK"* ]]; then
-#           echo "Health check passed."
-#         else
-#           echo "Health check failed."
-#           exit 1
-#         fi
-#       displayName: 'Health check'
+- stage: HealthCheck
+  jobs:
+  - job: HealthCheckJob
+    steps:
+    - task: UsePythonVersion@0
+      inputs:
+        versionSpec: '3.8'
+        addToPath: true
+    - script: |
+        # Perform a health check here, e.g., using a tool like curl or requests
+        # Wait for the service to start before checking
+        sleep 10  # Adjust the sleep duration as needed
+        response=$(curl -Is http://ec2-3-125-43-16.eu-central-1.compute.amazonaws.com/ | head -n 1)
+        if [[ $response == *"200 OK"* ]]; then
+          echo "Health check passed."
+        else
+          echo "Health check failed."
+          exit 1
+        fi
+      displayName: 'Health check'
 
 # - stage: Test
 #   jobs:
