[FIX]workflow action seperate build and deploy and health check logic

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,7 @@ on:
       - feature/*
 
 jobs:
-  build-deploy-and-run:
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -77,7 +77,12 @@ jobs:
           git config --local user.name github-actions[bot]
           git tag $new_version
           git push origin $new_version
+  
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
 
+    steps:
       - name: Deploy Docker Container on EC2
         env:
           EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
@@ -90,3 +95,16 @@ jobs:
           ssh -i ~/.ssh/devops.pem -o "StrictHostKeyChecking no" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "docker rm -f counter-service"
           ssh -i ~/.ssh/devops.pem -o "StrictHostKeyChecking no" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "docker pull muzaparoff/counter-service:$new_version"
           ssh -i ~/.ssh/devops.pem -o "StrictHostKeyChecking no" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "docker run --name=counter-service -d --restart=always -p 80:80 muzaparoff/counter-service:$new_version"
+      
+      - name: integration tests
+        run: |
+          new_version=${{ env.new_version }}
+          HEALTH_CHECK_URL="http://${{ secrets.EC2_HOST }}/health"
+          HEALTH_CHECK_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
+          
+          if [ $HEALTH_CHECK_RESPONSE -eq 200 ]; then
+            echo "Health check passed."
+          else
+            echo "Health check failed with status code $HEALTH_CHECK_RESPONSE."
+            exit 1
+          fi
